import Head from "next/head";
import Image from "next/image";

const Onboarding = () => {
  return (
    <div className="bg-gray-300 h-screen font-lato text-black">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="max-w-500px mx-auto bg-white h-full">
        <div>Alone we can do so little; together we can do so much</div>
        <div>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas
          vehicula aliquam consequat. Aliquam et nisi libero
        </div>
      </div>
    </div>
  );
};

export default Onboarding;
